// styles/device.ts — Styles specific to the device detail page

import React from "react";

export const deviceStyles: Record<string, React.CSSProperties> = {
  backBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.5rem",
    marginBottom: "1.5rem",
    background: "rgba(99,102,241,0.12)",
    border: "1px solid rgba(99,102,241,0.3)",
    borderRadius: "8px",
    padding: "0.5rem 1rem",
    color: "#a5b4fc",
    fontSize: "0.875rem",
    cursor: "pointer",
    transition: "background 0.2s",
    fontFamily: "inherit",
  },
  deviceTitle: {
    fontSize: "1.75rem",
    fontWeight: 700,
    background: "linear-gradient(90deg, #a5b4fc, #818cf8, #6366f1)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    marginBottom: "0.25rem",
  },
  badge: {
    display: "inline-block",
    padding: "0.2rem 0.65rem",
    borderRadius: "999px",
    fontSize: "0.75rem",
    fontWeight: 500,
    background: "rgba(99,102,241,0.2)",
    border: "1px solid rgba(99,102,241,0.3)",
    color: "#a5b4fc",
    marginRight: "0.5rem",
  },
  infoGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))",
    gap: "1rem",
    marginTop: "1.25rem",
  },
  infoItem: {
    background: "rgba(255,255,255,0.025)",
    border: "1px solid rgba(255,255,255,0.06)",
    borderRadius: "10px",
    padding: "0.875rem 1rem",
  },
  infoLabel: {
    fontSize: "0.7rem",
    textTransform: "uppercase" as const,
    letterSpacing: "0.08em",
    color: "#64748b",
    marginBottom: "0.35rem",
  },
  infoValue: {
    fontSize: "0.9rem",
    color: "#f1f5f9",
    fontWeight: 500,
    wordBreak: "break-all" as const,
  },
  infoValueMono: {
    fontSize: "0.8rem",
    color: "#94a3b8",
    fontFamily: "monospace",
    wordBreak: "break-all" as const,
  },
  chartWrapper: {
    marginTop: "0.5rem",
    height: "240px",
  },
  metricsTable: {
    width: "100%",
    borderCollapse: "collapse" as const,
    fontSize: "0.8rem",
    marginTop: "0.5rem",
  },
  th: {
    padding: "0.65rem 1rem",
    textAlign: "left" as const,
    fontSize: "0.7rem",
    textTransform: "uppercase" as const,
    letterSpacing: "0.08em",
    color: "#6366f1",
    borderBottom: "1px solid rgba(255,255,255,0.06)",
    background: "rgba(99,102,241,0.08)",
    whiteSpace: "nowrap" as const,
  },
  td: {
    padding: "0.6rem 1rem",
    borderBottom: "1px solid rgba(255,255,255,0.04)",
    color: "#cbd5e1",
    verticalAlign: "middle" as const,
  },
  tdMono: {
    padding: "0.6rem 1rem",
    borderBottom: "1px solid rgba(255,255,255,0.04)",
    color: "#94a3b8",
    fontFamily: "monospace",
    fontSize: "0.75rem",
    verticalAlign: "middle" as const,
  },
};
